### ISSUE TITLE
じゃんけんの結果をカウント,保存の実装

### ISSUE THREAD

**Issue by ayumuhack** [instigare/jagsc-jankenpon#3]
- [x] ブランチをmasterと分ける。
- [x] じゃんけんの勝敗をSharedPreferencesで保存し、Dialogで表示するようにする。

**Comment by ayumuhack** [comment]
@instigare ブランチの作成か、Collaboratorsに私の追加お願いします。
ブランチ出来たらそこに対してプルリク送ります。

**Comment by lvctr** [comment]
@ayumu1231 Collaborator招待送りましたのでご確認お願いします。
